### ISSUE TITLE
New Metacritic design issues 

### ISSUE THREAD

**Issue by DeMatthewBE** [hooshid/metacritic-scraper#1]
Hi there,

First of all thank you for this package. It saved me a lot of time the last few years.

Since a few days, Metacritic has updated their design (the ultimate fear of every scraping tool maker). 
Are you planning on updating the package?

Thank you!

--

Running the code throws an error:
Undefined property: stdClass::$mainEntity

On line 296 of src/Metacritic.php
```
    if ($html->findOneOrFalse('#__nuxt')) {
            $json = $this->jsonLD($response);
            $title = $json->mainEntity->name;
```

**Comment by arkamali** [comment]
@DeMatthewBE 
hi, thanks for comment, yes i need this package for my website, but i dont have time for now to update, may be you could help to update with new theme?

**Comment by arkamali** [comment]
hi, new theme changes update to package, enjoy!
